# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]


  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
        node-version: '14'

      - name: Run tests
        run: npm ci
        run: npm test

   
